namespace: fleet-mc-helm-example
targetCustomizations:
- name: amd64
  helm:
    values:
      image: "gcr.io/google-samples/gb-frontend:v4"
  clusterSelector:
    matchLabels:
      kubernetes.io/arch: amd64

- name: arm64
  helm:
    values:
      image: "gcr.io/google-samples/gb-frontend-arm64:v5"
  clusterSelector:
    matchLabels:
      kubernetes.io/arch: arm64
